name: face_recog
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http:
  camera:
  path_provider:
  image_picker:
  intl:
  file_picker:
  get:
  cupertino_icons:
  flutter_svg: 
  fluttertoast:
  dropdown_button2:
  lottie:
  shared_preferences: ^2.5.3
  image:
  tflite_flutter:
  permission_handler:
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
